### ISSUE TITLE
gov bot

### ISSUE THREAD

**Issue by Balugrizzly** [BloomGameStudio/BloomDiscordBot#3]
**3. gov bot**
- the main function here is to allow contributors to o a command flow to prepare a draft of a snapshot vote, properly

human:
```
!vote_draft
```

bot:
```
would you like to work on an existing draft or a new one? existing drafts are
:bulbasaur_emoji: blah blah
:bulbasaur_emoji_2:  give balu 1m
:bulbasaur_emoji_3: new
```

human
> selects new emoji

bot:
```
what is the name of this draft
```

bot:
```
is this budget or general?
```

----
human:
```
!budget
```

bot:
```
great! what is the abstract?
```

human:
```
hire pikachu for 2 units
```

bot:
```
can you provide some background?
```

human:
```
he has been crushing it
```

all of the above is in the "new" mode

edit mode would have commands from an emoji of which field to overwrite

lastly, there would be a `!publish_draft` or `!format_draft` thing to show a preview it, potentially which could be copypasta'd to snapshot
----- or better yet, posted directly by the bot if there is like 5+ emojis to confirm people are ready

**Comment by Sarahtonein** [comment]
Are you happy to close this issue now @Balugrizzly ?

**Comment by Balugrizzly** [comment]
Sure
