### ISSUE TITLE
Ignore Self Mentions

### ISSUE THREAD

**Issue by Balugrizzly** [BloomGameStudio/BloomDiscordBot#35]
The Bot currently notifies you for mentions that you did yourself which is redundant

**Comment by Sarahtonein** [comment]
Closing as this has been handled in recent PR Self mention

**Comment by Balugrizzly** [comment]
> Closing as this has been handled in recent PR Self mention

:) if you link this this will be done automatically and i won't get pinged 
apart from that i will periodically manage issues

@Sarahtonein
